# Generated by Django 2.2.10 on 2020-04-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productos', models.CharField(default='{}', max_length=200)),
                ('cliente', models.CharField(max_length=50)),
                ('precio', models.FloatField(default=0.0)),
            ],
        ),
    ]
