# Generated by Django 2.2.10 on 2020-06-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_tienda', '0003_auto_20200602_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='desc',
            field=models.CharField(default='Hola', max_length=100),
        ),
    ]
