# Generated by Django 2.2.10 on 2020-06-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_tienda', '0004_producto_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='desc',
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(default='descripción', max_length=400),
        ),
    ]
